### ISSUE TITLE
No Gamepad found - Dual Shock 4 Controller

### ISSUE THREAD

**Issue by Rouex** [rtr46/meiki#1]
Its more like a feature request if you are open to that but it seems that the dualshock PS4 Controller does not work with this programm.

**Comment by rtr46** [comment]
Sadly I don't have a PS4 controller to test stuff, so it is not really possible for me to add support.

meiki uses XInput as a controller API on windows and it seem that the PS4 controller doesn't support that API. There are some tools around that however.

I can't test it myself, but something like this should enable you to use the PS4 controller with meiki: https://github.com/Ryochan7/DS4Windows
